### ISSUE TITLE
Blog function order

### ISSUE THREAD

**Issue by 89z** [eatonphil/gozip#1]
I was reading the blog post:

https://notes.eatonphil.com/implementing-zip-in-go-unzipping.html

and couldnt find the defintion of these functions that are used repeatedly:

https://github.com/eatonphil/gozip/blob/77d0d02d30fedcb703eb043abe6a08b5b810e39e/main.go#L35-L51

turns out they are at the very bottom of the post. I think it might be better to move them before first use, so people know what they are, before seeing them used.

**Comment by eatonphil** [comment]
Thanks! I added a note to the post saying the helpers would be defined later on down.
