### ISSUE TITLE
Dont load the whole zip in memory

### ISSUE THREAD

**Issue by richmans** [eatonphil/gozip#2]
Liked your blog but i was really surprised to see you loading the entire file into memory. Not sure what your goal is with this but generally its a better idea to seek and read only parts of the file as you need them to prevent running out of memory for large files.

Also if you use the central directory you can iterate over the file headers without the ugly header signature check.

**Comment by eatonphil** [comment]
> Liked your blog but i was really surprised to see you loading the entire file into memory. Not sure what your goal is with this but generally its a better idea to seek and read only parts of the file as you need them to prevent running out of memory for large files.

Just laziness on my part. Most projects on my personal Github are purely educational/not intended for serious use.

> without the ugly header signature check.

What's the ugly header signature check? Nothing seemed weird to me about iterating through files starting from 0 index.

**Comment by richmans** [comment]
In that case, consider this a comment and not really an issue :-) what i meant by "ugly" is that youre trying to parse a local header and if that fails, youre concluding that that must be the end of the file. You are also assuming that there are never any bytes between the end of the last file and the start of the next header. Reading the central directory will tell you exactly how many files there are and where their headers are.

**Comment by eatonphil** [comment]
> what i meant by "ugly" is that youre trying to parse a local header and if that fails, youre concluding that that must be the end of the file. 

Oh yeah that part :D . Yeah you're right I do mean to look into the central directory metadata.

**Comment by richmans** [comment]
I did some googling, and it seems that finding the start of the central directory also involves a fair amount of guesswork. I would call that a bad file format design...

**Comment by richmans** [comment]
I'm not sure why, but dissecting binary files continues to be fun :-) I rewrote the program to read data as needed. Curious to hear what you think.

**Comment by eatonphil** [comment]
> I did some googling, and it seems that finding the start of the central directory also involves a fair amount of guesswork. I would call that a bad file format design...


From what I understand the central directory should start after the last file contents. I need to implement it to prove that assumption.
